version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  recorder:
    build:
      context: ./recorder
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always

  stt_worker:
    build:
      context: ./stt_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    deploy:
      replicas: 2   # 개발 시에는 무시됨, Swarm/K8s에서만 적용
    restart: always

  analyzer_worker:
    build:
      context: ./analyzer_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always

  listener:
    build:
      context: ./listener
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: always