version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  recorder:
    build:
      context: ./recorder
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DOCKER=1   # ✅ 추가
    restart: always

  stt_worker1:
    build:
      context: ./stt_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DOCKER=1   # ✅ 추가
    restart: always

  stt_worker2:
    build:
      context: ./stt_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DOCKER=1   # ✅ 추가
    restart: always

  analyzer_worker:
    build:
      context: ./analyzer_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DOCKER=1   # ✅ 추가
    restart: always

  listener:
    build:
      context: ./listener
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - DOCKER=1   # ✅ 추가
    restart: always