version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  recorder:
    build:
      context: ./recorder
      dockerfile: recorder/Dockerfile
    depends_on:
      - redis

  stt_worker:
    build:
      context: ./stt_worker
      dockerfile: stt_worker/Dockerfile
    depends_on:
      - redis
    deploy:
      replicas: 2  # ✅ local에서는 의미 없음 (배포툴에서 사용됨)

  analyzer_worker:
    build:
      context: ./analyzer_worker
      dockerfile: analyzer_worker/Dockerfile
    depends_on:
      - redis

  listener:
    build:
      context: ./listener
      dockerfile: listener/Dockerfile
    depends_on:
      - redis