version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  recorder:
    build:
      context: ./recorder
      dockerfile: Dockerfile
    depends_on:
      - redis

  stt_worker:
    build:
      context: ./stt_worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    deploy:
      replicas: 2 #배포용

  analyzer_worker:
    build:
      context: ./analyzer_worker
      dockerfile: Dockerfile
    depends_on:
      - redis

  listener:
    build:
      context: ./listener
      dockerfile: Dockerfile
    depends_on:
      - redis
