version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  recorder:
    build:
      context: ./recorder
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  stt_worker1:
    build:
      context: ./stt_worker
    command: celery -A stt_worker worker --loglevel=info --concurrency=1 --pool=solo -n stt_worker1
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  stt_worker2:
    build:
      context: ./stt_worker
    command: celery -A stt_worker worker --loglevel=info --concurrency=1 --pool=solo -n stt_worker2
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  analyzer_worker:
    build:
      context: ./analyzer_worker
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  listener:
    build:
      context: ./listener
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always
