# =============================================
# ✅ 최종 docker-compose.yml (FastAPI 포함 버전)
# =============================================

version: '3.9'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always

  recorder:
    build:
      context: ./recorder
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  stt_worker1:
    build:
      context: ./stt_worker
    command: celery -A stt_worker worker --loglevel=info --concurrency=1 --pool=solo -n stt_worker1
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  stt_worker2:
    build:
      context: ./stt_worker
    command: celery -A stt_worker worker --loglevel=info --concurrency=1 --pool=solo -n stt_worker2
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  analyzer_worker:
    build:
      context: ./analyzer_worker
    command: celery -A analyzer_worker worker --loglevel=info --concurrency=1 --pool=solo -n analyzer_worker1
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  listener:
    build:
      context: ./listener
    command: python3 listener.py
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

  fastapi_service:
    build:
      context: ./fastapi_service
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - DOCKER=1
    depends_on:
      - redis
    restart: always

# ✅ fastapi_service 추가 → 웹으로 스마트폰 Mic → Redis audio_queue 전송
# ✅ 발표용 + Azure 배포용 완전체